language: ruby
sudo: false
before_install:
  - bundle update
before_script:
  - '$(cd spec/dummy HANAMI_ENV=test bundle exec hanami db create)'
  - '$(cd spec/dummy HANAMI_ENV=test bundle exec hanami db migrate)'
script:
  - 'HANAMI_ENV=test bundle exec rake spec'
rvm:
  - 2.3.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
